import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

// Regression guard for the RSA-OAEP modulus (P0: it was silently reverted to 1024
// in PR #29's net diff). Pinned so any future revert of the constant fails CI.
const here = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(here, '..', 'src', 'utils', 'crypto.ts'), 'utf8');

const modulusMatch = source.match(/modulusLength:\s*(\d+)/);
assert.ok(modulusMatch, 'src/utils/crypto.ts must define an RSA modulusLength');
assert.equal(Number(modulusMatch[1]), 2048, 'RSA-OAEP modulusLength must be 2048 bits');

// End-to-end sanity: the key pair generated by the module really is 2048-bit.
// Node strips the type annotations in crypto.ts natively (erasable TS syntax).
const { generateRsaKeyPair } = await import(join(here, '..', 'src', 'utils', 'crypto.ts'));
const keyPair = await generateRsaKeyPair();
const jwk = await crypto.subtle.exportKey('jwk', keyPair.publicKey);
// 2048-bit modulus = 256 bytes; base64url without padding = 4 * ceil(256 / 3) - 2 = 342
assert.equal(jwk.n.length, 342, 'generated RSA public key modulus must be 2048 bits');

console.log('ok - RSA-OAEP modulus is 2048 bits (constant + generated key)');
